### ISSUE TITLE
Signature verification Not working

### ISSUE THREAD

**Issue by sourabhmandal** [ukrocks007/ondc-node#1]
I figured that the apiKey parameter is not implicitly initialized because of which calls were failing. However even after providing the apiKey value on the creation of a new ONDC object the verification is failing at the gateway. This usually happens when the signature generated is invalid.

here is the screenshot
![image](https://user-images.githubusercontent.com/39632788/185743046-7e6a06ac-ba0e-4703-8c14-236d9df1c366.png)

we can have a video call if you want to, so that I can walk you through the issue.

**Comment by mshar899** [comment]
@sourabhmandal Were you able to properly setup this, I have some doubts regarding this.

**Comment by yashb042** [comment]
Following
